MetricsHub/community-connectors

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Linux/memory.awk
src/main/connector/system/System/System.yaml

- Developed Linux Connector
- Added system.yaml for common grounds with other potential system connectors

Issue #8: Added Linux Connector to Community repository

---

src/main/connector/system/Windows/Windows.yaml

Created Windows.yaml in community connectors.

Issue #20: Create Windows.yaml

---

src/main/connector/system/Windows/Windows.yaml

- Excluded CD/DVD drives from filesystem objects
- Fixed free memory collected
- Fixed 100 nanosecond to second conversion
- Fixed filesystem usage metric name

Issue #39: Windows connector feedback updates

---

src/main/connector/hardware/VMwareESXiDisksIPMI/VMwareESXiDisksIPMI.yaml
src/main/connector/hardware/VMwareESXiDisksStorage/VMwareESXiDisksStorage.yaml

Update detection criteria for VMware ESXi Disks (IPMI and Storage)
- Update detection criteria to include version 8

Issue #43: Update detection criteria for VMware ESXi Disks (IPMI and Storage)

---

src/main/connector/system/Windows/Windows.yaml

Updated the `Win32_LogicalDisk` query to add the file system type. 
Updated the `file_system` monitor's mapping to collect the `system.filesystem.type` attribute.

Issue #47: Added `file_system` type for Windows system

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

Fixing memory size on Linux and Windows connectors.

Issue #57: Fixing memory size on Linux and Windows connectors

---

pom.xml

* Updated report plugin section to use `metricshub-connector-maven-plugin` version 1.0.02.

Issue #69: Use MetricsHub Connector Maven Plugin version 1.0.02

---

pom.xml

* Updated POM to use Connector Maven Plugin version 1.0.03 for the documentation.

Issue #69: Use MetricsHub Connector Maven Plugin version 1.0.03

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/System/System.yaml
src/main/connector/system/Windows/Windows.yaml

The system_uptime metric provides the timestamp of the system's last boot. This metric is crucial for monitoring the system's uptime by offering the exact time at which the system was last restarted. Additionally, this metric includes labels that provide detailed information about the operating system.
Labels:
- name: The name of the operating system (e.g., "Debian GNU/Linux", "Microsoft Windows Server 2019 Standard")
- os_version: The version of the operating system (e.g., "6.1.0-18-amd64", "10.0.17763").
- version: The detailed version or release name of the OS (e.g., "12 (bookworm)", "17763").
- Value: The metric value is a timestamp representing the last boot time of the system, formatted in Unix epoch time.

Issue #85: Added new metrics system.uptime

---

src/main/connector/system/LinuxProcess/LinuxProcess.yaml
src/main/connector/system/LinuxService/LinuxService.yaml
src/main/connector/system/WindowsProcess/WindowsProcess.yaml
src/main/connector/system/WindowsService/WindowsService.yaml

* Added connector variables default values on `LinuxService`, `LinuxProcess`, `WindowsService` & `WindowsProcess`.
* Tested these connectors on MetricsHub Agent.
Tested all the modified connectors as well, everything worked perfectly!

Issue #122: Add default values for connector variables 

---

src/main/connector/system/LinuxService/LinuxService.yaml
src/main/connector/system/WindowsProcess/WindowsProcess.yaml
src/main/connector/system/WindowsService/WindowsService.yaml

* Tdded `disableAutoDetection` for `WindowsProcess`, `WindowsService` & `LinuxService`.
* Tested on Windows
- Both WindowsProcess & WindowsService not detected.

Issue #125: Disable automatic detection

---

pom.xml

This pull request includes a minor version update to the `metricshub-connector-maven-plugin` in the `pom.xml` file.
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L165-R165): Updated the `metricshub-connector-maven-plugin` version from `1.0.05` to `1.0.06`.

Issue #132: Use `metricshub-connector-maven-plugin` version 1.0.06

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/LinuxProcess/LinuxProcess.yaml
src/main/connector/system/LinuxService/LinuxService.yaml

* Fixed the typo.
* Tested the result on metricshub doc.

Issue #140: Fix `Platform` typo instead of `Platforms` on `Linux` & `LinuxService`

---

src/main/connector/system/Linux/Linux.yaml

This pull request includes an important update to the `src/main/connector/system/Linux/Linux.yaml` file, specifically within the `monitors` section. The change modifies the `awk` script used for processing disk usage information.
Key change:
* [`src/main/connector/system/Linux/Linux.yaml`](diffhunk://#diff-6d6e70c25f3246a9ae9889d976c332be4895e49b0b7605cbabe6dbc9f2ab4fa9L153-R153): Updated the `awk` script to correctly calculate the percentage of used and available space by using the sum of used and available space as the denominator.
Testing:
```bash
root@nb-debian:/opt/workspace/opentelemetry-collector-contrib# /usr/bin/df -B1
Filesystem       1B-blocks        Used  Available Use% Mounted on
udev            2053718016           0 2053718016   0% /dev
tmpfs            413818880 …
```

Issue #148: [Linux] Enhance filesystem utilization calculation

---

src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml

*  Updated MIB2, MIB2NT and MIB2Switch

Issue #169: MIB2, MIB2Switch, MIB2NT: Add interface ID, name, and alias as attributes

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

* Updated `windows.yaml` and `linux.yaml` connectors to collect `network.interface.name` metric.
* Tested on MetricsHub.

LinuxOs and WindowsOs connectors should use network.interface.name for system.network metrics

---

src/main/connector/system/Linux/Linux.yaml

* Updated `Linux.yaml` to use `disk.io.direction`.
* Replaced `:` by `=` in the physical_disk mapping.
* Tested on Prometheus, and everything is working well after the update.

Issue #178: Wrong `system.disk.*` metric attribute names and bad mapping syntax in LinuxOs

---

src/main/connector/system/Windows/Windows.yaml

In the `Windows` connector, convert `system.disk.io_time` and `system.disk.operation_time` from 100ns to seconds.
Also added `system.device` required attribute.

Issue #204: Windows: Fixed system.disk.io_time and system.disk.operation_time

---

src/main/connector/database/MySQL/MySQL.yaml
src/main/connector/semconv/Database.yaml

Updated MySQL.yaml and Database.yaml

Rename metric db.server.active_connections to db.server.current_connections in MySQL connector

---

src/main/connector/system/Linux/Linux.yaml

Fixed `system.disk.operation_time` metric name in Linux connector

Issue #215: Fixed `system.disk.operation_time` metric name in Linux connector

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

In `Windows.yaml`:
* Improved comments and formatting
* Split paging usage (per pagefile) paging activity (global) in 2 separate monitors
* Fixed the case when there is no pagefile
* Fixed pagefile usage unit (switched to `Win32_PageFileUsage` WMI class)
* Fixed paging activity calculation
In `Linux.yaml`:
* Simply aligned display name with Windows ("Linux System", to match with "Windows System")

Issue #220: Windows: fix paging metrics

---

src/main/connector/semconv/System.yaml
src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

Tested on Linux:
Tested on Windows:
> **Note**
> `system.network.bandwidth.utilization` is not calculated as it would need to leverage IO rates and it's more proper to calculate at query time based on absolute counters.

Issue #224: Linux, Windows: Collect system.network.bandwidth.limit

---

src/main/connector/semconv/Hardware.yaml

This pull request includes a minor correction to the `Hardware.yaml` file in the `semconv` connector. The change updates the unit of measurement for the `hw.network.dropped` metric from `{packet}` to `{packets}` to ensure proper pluralization.

Issue #250: Updated unit for hw.network.dropped to {packets}

---

src/main/connector/semconv/System.yaml

* Added `System.disk.limit` and `System.filesystem.limit` on the `System.yaml` semconv.
https://opentelemetry.io/docs/specs/semconv/system/system-metrics/#metric-systemdisklimit

Issue #277: SemConv: Update system metric names
