.gitignore
pom.xml
src/site/resources/css/site.css
src/site/site.xml

* Add MetricsHub Connector Maven Plugin configuration to pom.xml file.
* Update site.xml to generate documentation.
* Add bodyClass for better styling in site.xml file.
* Create site.css for consistent colors in syntax highlighting.

Issue #15: Generate documentation in MetricsHub Community Connectors

---

src/main/connector/hardware/DiskPart/DiskPart.yaml
src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/HyperV/HyperV.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2EntitySensor-header/MIB2EntitySensor-header.yaml
src/main/connector/hardware/MIB2Linux/MIB2Linux.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/VMwareESX5iLUN-header/VMwareESX5iLUN-header.yaml
src/main/connector/hardware/VMwareESXi-header/VMwareESXi-header.yaml
src/main/connector/hardware/VMwareESXiDisksStorage/VMwareESXiDisksStorage.yaml
src/main/connector/hardware/Virsh/Virsh.yaml
src/main/connector/hardware/WBEMGenDiskNT/WBEMGenDiskNT.yaml
src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
src/main/connector/hardware/WinStorageSpaces/WinStorageSpaces.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml

- Fixed sprintf quotation marks escapes
- Fixed join quotation marks escapes

Issue #25: fix sprintf and join escape strings in connectors

---

src/main/connector/hardware/DiskPart/DiskPart.yaml
src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/HyperV/HyperV.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/LinuxIPNetwork/LinuxIPNetwork.yaml
src/main/connector/hardware/LinuxIfConfigNetwork/LinuxIfConfigNetwork.yaml
src/main/connector/hardware/LinuxMultipath/LinuxMultipath.yaml
src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/VMwareESX4i/VMwareESX4i.yaml
src/main/connector/hardware/VMwareESXVMSNMP/VMwareESXVMSNMP.yaml
src/main/connector/hardware/VMwareESXi/VMwareESXi.yaml
src/main/connector/hardware/VMwareESXiDisksIPMI/VMwareESXiDisksIPMI.yaml
src/main/connector/hardware/VMwareESXiDisksStorage/VMwareESXiDisksStorage.yaml
src/main/connector/hardware/Virsh/Virsh.yaml
src/main/connector/hardware/WBEMGenDiskNT/WBEMGenDiskNT.yaml
src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
src/main/connector/hardware/WinStorageSpaces/WinStorageSpaces.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml

Refined connector information fields to match internal changes.

Issue #28: Refined connector information fields

---

src/main/connector/hardware/LinuxNetwork-header/LinuxNetwork-header.yaml
src/main/connector/hardware/MIB2EntitySensor-header/MIB2EntitySensor-header.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
src/main/connector/hardware/VMwareESX5iLUN-header/VMwareESX5iLUN-header.yaml

* Update constant references using the pattern ${constant::%s}

Issue #31: Update constant references

---

src/main/connector/system/Linux/Linux.yaml

- Fixed truncation of IDs by adding a sed command to handle a special character

Issue #36: Fixed truncation of IDs

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Linux/memory.awk
src/main/connector/system/Linux/network.awk

- Changed physical_disk monitor name to match windows monitor
- Fixed conversion of cpu time (parsec to s)

Issue #41: Linux connector feedback changes

---

src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/MIB2EntitySensor-header/MIB2EntitySensor-header.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/VMwareESXi-header/VMwareESXi-header.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml

* Added `milliVolt2Volt` conversion on `hw.voltage` and `hw.voltage.limit` values to convert values to V.

Issue #62: Adding Voltage conversion from MilliVolt to Volt

---

src/main/connector/hardware/DiskPart/DiskPart.yaml
src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/HyperV/HyperV.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/LinuxMultipath/LinuxMultipath.yaml
src/main/connector/hardware/LinuxNetwork-header/LinuxNetwork-header.yaml
src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2EntitySensor-header/MIB2EntitySensor-header.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/VMwareESX5iLUN-header/VMwareESX5iLUN-header.yaml
src/main/connector/hardware/VMwareESXi-header/VMwareESXi-header.yaml
src/main/connector/hardware/VMwareESXiDisksIPMI/VMwareESXiDisksIPMI.yaml
src/main/connector/hardware/Virsh/Virsh.yaml
src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml
src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

Replace leftConcat, rightConcat and osCommand by prepend, append and commandLine in all connectors to remove deprecated computes and sources.

Issue #56: Replace leftConcat, rightConcat and osCommand by prepend, append and commandLine

---

src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml

Added network bandwidth to MIB2 connectors

Issue #67: Added network bandwidth to MIB2 connectors

---

pom.xml

* Defined sourceDirectory telling the maven-source-plugin where to find the sources.

Issue #81: Fixed connector source artifact

---

src/main/connector/hardware/MIB2Linux/MIB2Linux.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml

* Surrounded some Regular Expressions with double quotes as in HDFs.

Issue #95: MIB2NT: Bad ExcludeMatchingLines regex

---

src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/Windows/Windows.yaml

* Refactor Linux.yaml
* Refactor Windows.yaml

Issue #101: Fix incorrect memory metric naming

---

src/main/connector/system/Windows/Windows.yaml
src/main/connector/system/WindowsProcess/WindowsProcess.yaml

Issue #94: Create windows process connector

---

src/main/connector/hardware/DiskPart/DiskPart.yaml
src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/HyperV/HyperV.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/LinuxIPNetwork/LinuxIPNetwork.yaml
src/main/connector/hardware/LinuxIfConfigNetwork/LinuxIfConfigNetwork.yaml
src/main/connector/hardware/LinuxMultipath/LinuxMultipath.yaml
src/main/connector/hardware/LinuxNetwork-header/LinuxNetwork-header.yaml
src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2Linux/MIB2Linux.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/Virsh/Virsh.yaml
src/main/connector/hardware/WBEMGenDiskNT/WBEMGenDiskNT.yaml
src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
src/main/connector/hardware/WinStorageSpaces/WinStorageSpaces.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml
src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/LinuxService/LinuxService.yaml
src/main/connector/system/Windows/Windows.yaml

* Added tags to community connectors based on the tags list.
* Tested using metricshub connectors maven plugin which regrouped all the connectors with the same tag.

Issue #102: Add tags to community connectors

---

src/main/connector/hardware/LinuxNetwork-header/LinuxNetwork-header.yaml
src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml

Updated LinuxNetwork-header.yaml, MIB2-header.yaml, WBEMGenHBA.yaml and WBEMGenNetwork.yaml

Issue #114: Update hw.network.bandwidth.limit mapping

---

src/main/connector/hardware/Hardware/Hardware.yaml

* Fixed hw.vm.power_ratio metric unit

Issue #120: Fixed `hw.vm.power_ratio` metric unit

---

src/main/connector/system/Linux/Linux.yaml

Issue #143:  Remove Service Monitor Job from Linux Connector

---

src/main/connector/hardware/DiskPart/DiskPart.yaml
src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/HyperV/HyperV.yaml
src/main/connector/hardware/IpmiTool/IpmiTool.yaml
src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
src/main/connector/hardware/LinuxIPNetwork/LinuxIPNetwork.yaml
src/main/connector/hardware/LinuxIfConfigNetwork/LinuxIfConfigNetwork.yaml
src/main/connector/hardware/LinuxMultipath/LinuxMultipath.yaml
src/main/connector/hardware/MIB2/MIB2.yaml
src/main/connector/hardware/MIB2Linux/MIB2Linux.yaml
src/main/connector/hardware/MIB2NT/MIB2NT.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
src/main/connector/hardware/Virsh/Virsh.yaml
src/main/connector/hardware/WBEMGenDiskNT/WBEMGenDiskNT.yaml
src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
src/main/connector/hardware/WinStorageSpaces/WinStorageSpaces.yaml
src/main/connector/hardware/lmsensors/lmsensors.yaml
src/main/connector/system/Linux/Linux.yaml
src/main/connector/system/LinuxProcess/LinuxProcess.yaml
src/main/connector/system/LinuxService/LinuxService.yaml
src/main/connector/system/Windows/Windows.yaml
src/main/connector/system/WindowsProcess/WindowsProcess.yaml
src/main/connector/system/WindowsService/WindowsService.yaml

* Update platforms field in connectors.
* Tested the results on MetricsHub Enterprise using MetricsHub Connector Maven Plugin.

Issue #158: Update platforms for community connectors

---

src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml

* Updated MIB2Switch.yaml and GenericSwitchEnclosure.yaml

Issue #163: Add Arista Platform to MIB2Switch and GenericSwitchEnclosure

---

src/main/connector/hardware/Storage/Storage.yaml

Issue #168: Remove storage.mapped from Storage semconv

---

src/main/connector/hardware/GenericUPS/GenericUPS.yaml
src/main/connector/hardware/GenericUPS/voltage.awk

* Updated GenericUPS.yaml and voltage.awk

Issue #173: Generic UPS: Some voltage sensors are not discovered

---

src/site/markdown/develop/connector.md
src/site/markdown/develop/sources/awk.md
src/site/markdown/develop/sources/command-line.md
src/site/markdown/develop/sources/http.md
src/site/markdown/develop/sources/internal-db-query.md
src/site/markdown/develop/sources/ipmi.md
src/site/markdown/develop/sources/snmp-get.md
src/site/markdown/develop/sources/snmp-table.md
src/site/markdown/develop/sources/sql.md
src/site/markdown/develop/sources/table-join.md
src/site/markdown/develop/sources/table-union.md
src/site/markdown/develop/sources/wbem.md
src/site/markdown/develop/sources/wmi.md
src/site/site.xml

Add Awk Source page to the the connector developer's guide. 
Correct some issues with the SQL and InternalDbQueries sources. 
Correction of a few issues throughout the site.

Issue # 184 Add Awk Source page to the connector developer's guide

---

src/main/connector/database/MySQL/MySQL.yaml

Issue #190: Add db.server.name as an attribute in MySQL

---

src/main/connector/semconv/Database.yaml

* Add new database metrics to Database.yaml

Issue #188: Update database yaml

---

src/main/connector/hardware/SmartMonLinux/SmartMonLinux.yaml
src/main/connector/hardware/SmartMonLinux/physicalDiskSmartHealth.sh
src/main/connector/hardware/SmartMonLinux/physicalDiskStatusInformation.sh
src/main/connector/hardware/SmartMonLinux/smartctlAll.sh
src/main/connector/hardware/SmartMonLinux/smartctlTempColl.sh
src/main/connector/hardware/SmartMonLinux/smartctlTempDisc.sh

* Fix physical disks retrieval logic
* Update temperature retrieval logic
* Rename embedded files and set their extension to .sh
* Move SmartMonLinux from enterprise connectors to community connectors

Issue #202: Fix physical disks and temperature issues for SmartMonLinux

---

src/main/connector/system/Linux/Linux.yaml

Various improvements in the Linux connector wrt physical disks:
* Converted disk activity stats from ms to s. 
* Added support for NVMe. 
* Removed logical disks and partitions.

Issue #205: Linux: Various improvements to physical disk monitoring

---

src/main/connector/system/Windows/Windows.yaml

Issue #229: Windows: Fix system.paging.type

---

src/main/connector/system/Linux/Linux.yaml

See issue #231 for (shameful) details. 🤦‍♂️

Issue #231: Linux: Fix attribute name for system.paging.operations

---

src/main/connector/hardware/DiskPart/DiskPart.yaml

Issue #210: DiskPart: it is tested remotely whereas it should work only locally

---

src/main/connector/hardware/MIB2-header/MIB2-header.yaml
src/main/connector/semconv/Hardware.yaml

* Select the columns ifinDiscards and ifOutDiscards in source(1) of collect
* Define a new metric
* Update existing columns numbers
* Update comments

Issue #233: Add metrics for ifinDiscards and ifOutDiscards

---

src/main/connector/database/MySQL/MySQL.yaml
src/main/connector/database/PostgreSQL/PostgreSQL.yaml
src/main/connector/semconv/Database.yaml

Issue #242: Add new metrics for Informix in database.yaml

---

src/site/markdown/develop/references.md

Issue #278: Docs: add support for ${protocol::PROTOCOL.PROPERTY} reference in connectors
